knpu_oauth2_client:
    clients:
        twitch:
            use_state: false
            type: generic
            provider_class: App\Security\Provider\TwitchProvider
            client_id: '%env(OAUTH_TWITCH_ID)%'
            client_secret: '%env(OAUTH_TWITCH_SECRET)%'
            redirect_route: twitch_connect_check
            redirect_params: {}