image: php:7.3

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &build-sonarcloud
        name: Build and analyze on SonarCloud
        caches:
          - composer
          - sonar
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - pipe: sonarsource/sonarcloud-scan:1.0.1
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: '-Dsonar.sources=src -Dsonar.tests=src -Dsonar.test.inclusions="**/tests/**,**/*.spec.ts" -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
    - step: &check-quality-gate-sonarcloud
        name: Check the Quality Gate on SonarCloud
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.3
    - step: &deploy-production
        name: Deploy to production
        trigger: manual
        deployment: production
        script:
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: $USER
              SERVER: $HOST
              PORT: $PORT
              MODE: 'command'
              COMMAND: './deploy-panel.sh'
pipelines:
  branches:
    master:
      - step: *build-sonarcloud
      - step: *check-quality-gate-sonarcloud
      - step: *deploy-production

  pull-requests:
    '**':
      - step: *build-sonarcloud
      - step: *check-quality-gate-sonarcloud
